import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: text('id').primaryKey(),
  email: text('email').unique().notNull(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  role: text('role', { enum: ['user', 'admin'] }).notNull().default('user'),
  password: text('password').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const useCases = sqliteTable('use_cases', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description').notNull(),
  whatWasBuilt: text('what_was_built').notNull(),
  keyLearnings: text('key_learnings').notNull(),
  metrics: text('metrics').notNull(),
  category: text('category').notNull(),
  aiTool: text('ai_tool').notNull(),
  department: text('department').notNull(),
  impact: text('impact').notNull(),
  effort: text('effort').notNull(),
  status: text('status').notNull(),
  tags: text('tags').notNull(),
  submittedBy: text('submitted_by').notNull(),
  submitterTeam: text('submitter_team').notNull(),
  submittedById: text('submitted_by_id').references(() => users.id).notNull(),
  approvalStatus: text('approval_status').notNull(),
  reviewedBy: text('reviewed_by'),
  reviewNotes: text('review_notes'),
  reviewedAt: text('reviewed_at'),
  aiReadinessScore: integer('ai_readiness_score'),
  actualCosts: text('actual_costs'),
  assessmentId: text('assessment_id'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const refreshTokens = sqliteTable('refresh_tokens', {
  id: text('id').primaryKey(),
  token: text('token').notNull().unique(),
  userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  expiresAt: text('expires_at').notNull(),
  createdAt: text('created_at').notNull(),
});

export const prompts = sqliteTable('prompts', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  content: text('content').notNull(),
  description: text('description').notNull(),
  problemBeingSolved: text('problem_being_solved').notNull(),
  effectivenessRating: integer('effectiveness_rating').notNull(),
  tips: text('tips').notNull(),
  category: text('category').notNull(),
  aiTool: text('ai_tool').notNull(),
  useCaseId: text('use_case_id').references(() => useCases.id),
  tags: text('tags').notNull(),
  submittedBy: text('submitted_by').notNull(),
  submittedById: text('submitted_by_id').references(() => users.id).notNull(),
  approvalStatus: text('approval_status').notNull(),
  reviewedBy: text('reviewed_by'),
  reviewNotes: text('review_notes'),
  reviewedAt: text('reviewed_at'),
  rating: real('rating').notNull().default(0),
  ratingCount: integer('rating_count').notNull().default(0),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
